{
    'name': 'Elemento ERP Contabilidad',
    'version': '1.0',
    'summary': 'Instala Modulos de Contabilidad Elemento.',
    'category': 'Elemento Custom',
    'depends': [
        'account_usability',
        'product_category_tax',
        'account_move_print',
        'account_move_post_date_user',
        'account_move_line_sale_info',
        'account_move_line_purchase_info',
#        'account_dashboard_banner_mis_builder',
#        'account_dashboard_banner',
        'account_financial_report',
        'mis_template_financial_report',
        'partner_statement',
        'account_reconcile_analytic_tag',
        'account_reconcile_model_oca',
        'account_reconcile_oca',
        'account_statement_import_file_reconcile_oca',
        'account_statement_import_file',
        'account_statement_import_camt54',
        'account_statement_import_camt',
        'account_statement_import_base',
        'account_statement_import_ofx',
        'account_payment_show_invoice',
        'account_payment_widget_amount',
#        'account_due_list',
        'account_payment_method_base',
        'account_payment_partner',
        'account_payment_purchase',
        'account_payment_sale',
#        'product_form_account_move_line_link',
#        'stock_account_move_reset_to_draft',
    ],
    'installable': True,
    'application': True,
}

