{
    'name': 'Elemento ERP Ventas',
    'version': '1.0',
    'summary': 'Instala Modulos de Ventas Elemento.',
    'category': 'Elemento Custom',
    'depends': [
        'base_location',
        'base_location_geonames_import',
        'partner_property',
        'partner_supplier_ref',
        'partner_vat_unique',
        'partner_firstname',
        'partner_external_map',
        'base_partner_sequence',
        'base_country_state_translatable',
        'partner_category_type',
        'partner_company_default',
        'partner_company_type',
        'partner_contact_access_link',
        'sale_quotation_number',
        'sale_order_product_availability_inline',
        'sale_order_line_sequence',
        'sale_order_line_remove',
        'sale_order_line_chained_move',
    ],
    'installable': True,
    'application': True,
}